package cn.timelessmc.teleport.warp;

import java.io.IOException;
import java.io.OutputStream;
import java.util.List;
import java.util.Properties;
import java.util.TreeMap;

public class WarpEntryMap extends TreeMap<String, WarpEntry> {
    private final List<String> types;

    public WarpEntryMap(Properties rawMap, List<String> types) {
        rawMap.forEach((key, value) -> this.put((String) key, WarpEntry.parse((String) value)));
        this.types = types;
    }

    public List<String> getTypes() {
        return this.types;
    }

    public Properties toProperties() {
        Properties res = new Properties();
        this.forEach((key, value) -> res.put(key, value.toString()));
        return res;
    }

    public synchronized void saveToStream(OutputStream stream) throws IOException {
        this.toProperties().store(stream, "Warp List generated by tlmc-tp-spigot. Don't modify!");
    }
}
